// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Chat.MessageView = (function(_super) {

    __extends(MessageView, _super);

    function MessageView() {
      var node;
      MessageView.__super__.constructor.apply(this, arguments);
      node = this.get("node");
    }

    return MessageView;

  })(Batman.View);

  Chat.UserView = (function(_super) {

    __extends(UserView, _super);

    function UserView() {
      var node;
      UserView.__super__.constructor.apply(this, arguments);
      node = this.get("node");
    }

    return UserView;

  })(Batman.View);

  Chat.TaskView = (function(_super) {

    __extends(TaskView, _super);

    function TaskView() {
      var node;
      TaskView.__super__.constructor.apply(this, arguments);
      node = this.get("node");
    }

    return TaskView;

  })(Batman.View);

}).call(this);
